spring:
  application:
    name: vhr

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/vhr?characterEncoding=utf-8
    username: root
    password: 123123

  security:
    jwt:
      key: 1x1
      expire: 7
    filter:
      order: -100

  #Redis
  data:
    redis:
      host: localhost
      port: 6379
      password: 123123
      database: 0
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: 18000
          min-idle: 0


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #sql日志
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: delFlag